export const GET_RECOMMENDED_MOVIES_REQUEST = "GET_RECOMMENDED_MOVIES_REQUEST";
export const GET_RECOMMENDED_MOVIES_SUCCESS = "GET_RECOMMENDED_MOVIES_SUCCESS";
export const GET_RECOMMENDED_MOVIES_FAILURE = "GET_RECOMMENDED_MOVIES_FAILURE";

export const TOGGLE_FAVORITE_MOVIE = "TOGGLE_FAVORITE_MOVIE";

export const SHOW_ALERT_POPUP = "SHOW_ALERT_POPUP";
export const HIDE_ALERT_POPUP = "HIDE_ALERT_POPUP";
